name: Deploy docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Bun.sh
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --production

      - name: Build
        run: bun run build

      - name: Deploy storybook
        run: bun run deploy-storybook -- --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
